os:
  editCommand: '~/.local/bin/lvim' # as an example
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}'
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
notARepository: 'skip' # one of: 'prompt' | 'create' | 'skip' | 'quit'
